health_check_port: 8080
server_config:
  channel_size: 100
  db_config:
    type: "postgres_config"
    connection_string: postgresql://postgres@localhost:5432/nft_marketplace3
  transaction_stream_config:
    starting_version: 2382373209
    request_ending_version: 2382373209
    indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
    auth_token: aptoslabs_Kfa6xiJowsr_MfXBcBgxUX2RGNDYNxZGirvwPEQRwxARE
    request_name_header: "nft_marketplace_processor"
  nft_marketplace_config:
    marketplace_name: "wapal"
    contract_address: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9"
    event_config:
      creator_address: "$.token_metadata.creator_address"
      # collection_id: "$.token_id.token_data_id"
      # token_data_id: "$.token_id"
      # token_offer_id: "$.token_offer" # not. sure if this is needed
      # collection_offer_id: "$.collection_offer" # not. sure if this is needed
      token_name: "$.token_metadata.token_name"
      property_version: "$.token_metad.property_version"
      price: "$.price"
      token_amount: "$.token_amount"
      seller: "$.seller"
      buyer: "$.purchaser"
      collection_name: "$.token_metadata.collection_name"
    listing_config:
      cancel_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingCanceledEvent"
      fill_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingFilledEvent" 
      place_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingPlacedEvent"
    offer_config:
      cancel_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferCanceledEvent"
      fill_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferFilledEvent"
      place_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferPlacedEvent"
    collection_offer_config:
      cancel_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferCanceledEvent"
      fill_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferFilledEvent" 
      place_event: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferPlacedEvent"
      collection_name: "$.collection_metadata.collection_name"
      # deadline: "$.deadline"
      # collection_offer_id: "$.collection_offer"
      creator_address: "$.collection_metadata.creator_address"