health_check_port: 8080
server_config:
  channel_size: 100
  db_config:
    type: "postgres_config"
    connection_string: postgresql://postgres@localhost:5432/nft_marketplace
  transaction_stream_config:
    starting_version: <starting_version>
    request_ending_version: <request_ending_version>
    indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
    auth_token: <auth_token>
    request_name_header: "nft_marketplace_processor"
  nft_marketplace_configs:
    marketplaces:
      - name: "topaz"
        event_types:
          - type: "listing"
            cancel: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::DelistEvent"
            fill: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BuyEvent"
            place: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::ListEvent"
          - type: "token_offer"
            cancel: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelBidEvent"
            fill: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BidEvent"
            place: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::SellEvent"
          - type: "collection_offer"
            cancel: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelCollectionBidEvent"
            fill: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::FillCollectionBidEvent"
            place: "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CollectionBidEvent"
        tables:
          nft_marketplace_activities:
            columns:
              collection_id:
                path: ["$.collection_id", "$.collection_inner"]
              token_data_id:
                path: ["$.token_inner"]
              token_name:
                path: ["$.token_id.token_data_id.name"]
              creator_address:
                path: ["$.token_id.token_data_id.creator", "$.creator"]
              collection_name:
                path: ["$.token_id.token_data_id.collection", "$.collection_metadata.collection_name", "$.collection_name"]
              price:
                path: ["$.price"]
              buyer:
                path: ["$.buyer"]
              seller:
                path: ["$.seller"]
              token_amount:
                path: ["$.amount"]
              listing_id:
                path: ["$.listing_id"]
              offer_id:
                path: ["$.bid_id"]
              expiration_time:
                path: ["$.deadline"]
      - name: "tradeport"
        event_types:
          - type: "listing"
            cancel: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::listings::DeleteListingEvent"
            fill: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::listings::BuyEvent"
            place: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::listings::InsertListingEvent"
          - type: "token_offer"
            cancel: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings::DeleteTokenBidEvent"
            fill: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings::AcceptTokenBidEvent"
            place: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings::InsertTokenBidEvent"  
          - type: "collection_offer"
            cancel: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings::DeleteCollectionBidEvent"
            fill: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings::AcceptCollectionBidEvent"
            place: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings::InsertCollectionBidEvent"
        tables:
          nft_marketplace_activities:
            columns:
              collection_id:
                path: ["$.collection_id", "$.collection_inner"]
              token_data_id:
                path: ["$.token_inner"]
              token_name:
                path: ["$.token_id.token_data_id.name"]
              creator_address:
                path: ["$.token_id.token_data_id.creator", "$.collection_id.collection_creator"]
              collection_name:
                path: ["$.token_id.token_data_id.collection", "$.collection_id.collection_name"]
              price:
                path: ["$.price"]
              buyer:
                path: ["$.bid_buyer"]
              seller:
                path: ["$.bid_seller", "$.owner"]
              token_amount:
                path: ["$.amount"]
              listing_id:
                path: []
              offer_id:
                path: []
              expiration_time:
                path: ["$.deadline"]
  
      - name: "tradeport_v2"
        event_types:
          - type: "listing"
            cancel: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::listings_v2::DeleteListingEvent"
            fill: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::listings_v2::BuyEvent"
            place: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::listings_v2::InsertListingEvent"
          - type: "token_offer"
            cancel: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings_v2::DeleteTokenBidEvent"
            fill: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings_v2::AcceptTokenBidEvent"
            place: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings_v2::InsertTokenBidEvent"
          - type: "collection_offer"
            cancel: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings_v2::DeleteCollectionBidEvent"
            fill: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings_v2::AcceptCollectionBidEvent"
            place: "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26::biddings_v2::InsertCollectionBidEvent"
        tables:
          nft_marketplace_activities:
            columns:
              collection_id:
                path: ["$.collection_id", "$.collection.inner"]
              token_data_id:
                path: ["$.token.inner"]
              token_name:
                path: ["$.token_metadata.token_name"]
              creator_address:
                path: ["$.token_metadata.creator_address"]
              collection_name:
                path: ["$.token_metadata.collection_name"]
              price:
                path: ["$.price"]
              buyer:
                path: ["$.bid_buyer", "$.buyer"]
              seller:
                path: ["$.bid_seller", "$.seller"]
              token_amount:
                path: ["$.token_amount"]
              listing_id:
                path: ["$.listing.inner"]
              offer_id:
                path: ["$.bid.inner"]
              expiration_time:
                path: []

          current_nft_marketplace_listings:
            columns:
              collection_id:
                source: "write_set_changes" # by default we look at events if not provided
                resource_type: "0x4::token::Token"
                path: ["$.collection.inner"]
            
          current_nft_marketplace_token_offers:
            columns:
              token_name:
                source: "write_set_changes"
                resource_type: "0x4::token::TokenIdentifiers"
                path: ["$.name.value"]
                event_type: "fill_token_offer"

          current_nft_marketplace_collection_offers:
            columns:
              collection_id:
                source: "write_set_changes"
                resource_type: "0x4::token::Token"
                path: ["$.collection.inner"]
                event_type: "fill_collection_offer"

      - name: "wapal"
        event_types:
          - type: "listing"
            cancel: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingCanceledEvent"
            fill: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingFilledEvent"
            place: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::ListingPlacedEvent"
          - type: "token_offer"
            cancel: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferCanceledEvent"
            fill: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferFilledEvent"
            place: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::TokenOfferPlacedEvent"
          - type: "collection_offer"
            cancel: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferCanceledEvent"
            fill: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferFilledEvent"
            place: "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9::events::CollectionOfferPlacedEvent"
        tables:
          nft_marketplace_activities:
            columns:
              collection_id:
                path: ["$.collection_id", "$.collection_metadata.collection.vec[0].inner", "$.token_metadata.collection.vec[0].inner"]
              token_data_id:
                path: ["$.token_metadata.token.vec[0].inner"]
              token_name:
                path: ["$.token_metadata.token_name"]
              creator_address:
                path: ["$.token_metadata.creator_address", "$.collection_metadata.creator_address"]
              collection_name:
                path: ["$.token_metadata.collection_name", "$.collection_metadata.collection_name"]
              price:
                path: ["$.price"]
              buyer:
                path: ["$.purchaser"]
              seller:
                path: ["$.seller"]
              token_amount:
                path: ["$.token_amount"]
              listing_id:
                path: ["$.listing"]
              offer_id:
                path: ["$.token_offer", "$.collection_offer"]
              expiration_time:
                path: []
      - name: "bluemove"
        event_types:
          - type: "listing"
            cancel: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::marketplaceV2::DelistEvent"
            fill: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::marketplaceV2::BuyEvent"
            place: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::marketplaceV2::ListEvent"
          - type: "token_offer"
            cancel: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::offer_lib::CancelOfferEvent"
            fill: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::offer_lib::AcceptOfferEvent"
            place: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::offer_lib::OfferEvent"
          - type: "collection_offer"
            cancel: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::offer_lib::CancelOfferCollectionEvent" 
            fill: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::offer_lib::AcceptOfferCollectionEvent" 
            place: "0xd1fd99c1944b84d1670a2536417e997864ad12303d19eac725891691b04d614e::offer_lib::OfferCollectionEvent"
        tables:
          nft_marketplace_activities:
            columns:
              collection_id:
                path: ["$.collection_id", "$.collection.inner"]
              token_data_id:
                path: ["$.token.inner"]
              token_name:
                path: ["$.token_id.token_data_id.name", "$.id.token_data_id.name"]
              creator_address:
                path: ["$.token_id.token_data_id.creator", "$.offer_collection_item.creator_address", "$.id.token_data_id.creator"]
              collection_name:
                path: ["$.token_id.token_data_id.collection", "$.offer_collection_item.collection_name", "$.id.token_data_id.collection"]
              price:
                path: ["$.amount", "$.offer_collection_item.amount_per_item"]
              buyer:
                path: ["$.offerer", "$.offer_collection_item.offerer", "$.buyer_address"]
              seller:
                path: ["$.seller_address"]
              token_amount:
                path: ["$.offer_collection_item.quantity_offer_items"]
              listing_id:
                path: ["$.listing.inner"]
              offer_id:
                path: ["$.offer_id", "$.offer_collection_id"]
              expiration_time:
                path: []
                