pub mod db;
pub mod utils;

// Need to use this for because schema.rs uses the macros and is autogenerated
// #[macro_use]
// extern crate diesel;
#[path = "db/schema.rs"]
pub mod schema;

pub mod config;
pub mod processors;
