nft_marketplace_config:
  - name: "topaz"
    event_model_mapping:
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::ListEvent": PlaceListing
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::DelistEvent": CancelListing
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BuyEvent": FillListing
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BidEvent": PlaceTokenOffer
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelBidEvent": CancelTokenOffer
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::SellEvent": PlaceCollectionOffer
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CollectionBidEvent": PlaceCollectionOffer  
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::FillCollectionBidEvent": FillCollectionOffer
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelCollectionBidEvent": CancelCollectionOffer
    events:
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::ListEvent":
        event_fields:
          "$.listing_id":
            - table: activities
              column: listing_id
          - table: current_nft_marketplace_listings
            column: listing_id
        "$.owner":
          - table: activities
            column: seller
          - table: current_nft_marketplace_listings
            column: seller
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_listings
            column: price
        "$.token_inner":
          - table: activities
            column: token_data_id
          - table: current_nft_marketplace_listings
            column: token_data_id
        "$.token_id.token_data_id.name":
          - table: activities
            column: token_name
        "$.token_id.token_data_id.creator":
          - table: activities
            column: creator_address
        "$.token_id.token_data_id.collection":
          - table: activities
            column: collection_name
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_listings
            column: collection_id
        "$.amount":
          - table: activities
            column: token_amount
          - table: current_nft_marketplace_listings
            column: token_amount

      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::DelistEvent":
        "$.listing_id":
          - table: activities
            column: listing_id
          - table: current_nft_marketplace_listings
            column: listing_id
        "$.owner":
          - table: activities
            column: seller
          - table: current_nft_marketplace_listings
            column: seller
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_listings
            column: price
        "$.token_inner":
          - table: activities
            column: token_data_id
          - table: current_nft_marketplace_listings
            column: token_data_id
        "$.token_id.token_data_id.name":
          - table: activities
            column: token_name
        "$.token_id.token_data_id.creator":
          - table: activities
            column: creator_address
        "$.token_id.token_data_id.collection":
          - table: activities
            column: collection_name
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_listings
            column: collection_id
        "$.amount":
          - table: activities
            column: token_amount
          - table: current_nft_marketplace_listings
            column: token_amount

      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BuyEvent":
        "$.listing_id":
          - table: activities
            column: listing_id
          - table: current_nft_marketplace_listings
            column: listing_id
        "$.seller":
          - table: activities
            column: seller
          - table: current_nft_marketplace_listings
            column: seller
        "$.buyer":
          - table: activities
            column: buyer
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_listings
            column: price
        "$.token_inner":
          - table: activities
            column: token_data_id
          - table: current_nft_marketplace_listings
            column: token_data_id
        "$.token_id.token_data_id.name":
          - table: activities
            column: token_name
        "$.token_id.token_data_id.creator":
          - table: activities
            column: creator_address
        "$.token_id.token_data_id.collection":
          - table: activities
            column: collection_name
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_listings
            column: collection_id
        "$.amount":
          - table: activities
            column: token_amount
          - table: current_nft_marketplace_listings
            column: token_amount

      # Token Offers
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BidEvent":
        "$.bid_id":
          - table: activities
            column: offer_id
          - table: current_nft_marketplace_token_offers
            column: offer_id
        "$.buyer":
          - table: activities
            column: buyer
          - table: current_nft_marketplace_token_offers
            column: buyer
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_token_offers
            column: price
        "$.token_inner":
          - table: activities
            column: token_data_id
          - table: current_nft_marketplace_token_offers
            column: token_data_id
        "$.token_id.token_data_id.name":
          - table: activities
            column: token_name
          - table: current_nft_marketplace_token_offers
            column: token_name
        "$.token_id.token_data_id.creator":
          - table: activities
            column: creator_address
        "$.token_id.token_data_id.collection":
          - table: activities
            column: collection_name
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_token_offers
            column: collection_id
        "$.deadline":
          - table: activities
            column: expiration_time

      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelBidEvent":
        "$.bid_id":
          - table: activities
            column: offer_id
          - table: current_nft_marketplace_token_offers
            column: offer_id
        "$.buyer":
          - table: activities
            column: buyer
          - table: current_nft_marketplace_token_offers
            column: buyer
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_token_offers
            column: price
        "$.token_inner":
          - table: activities
            column: token_data_id
          - table: current_nft_marketplace_token_offers
            column: token_data_id
        "$.token_id.token_data_id.name":
          - table: activities
            column: token_name
          - table: current_nft_marketplace_token_offers
            column: token_name
        "$.token_id.token_data_id.creator":
          - table: activities
            column: creator_address
        "$.token_id.token_data_id.collection":
          - table: activities
            column: collection_name
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_token_offers
            column: collection_id

      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::SellEvent":
        "$.bid_id":
          - table: activities
            column: offer_id
          - table: current_nft_marketplace_token_offers
            column: offer_id
        "$.buyer":
          - table: activities
            column: buyer
          - table: current_nft_marketplace_token_offers
            column: buyer
        "$.seller":
          - table: activities
            column: seller
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_token_offers
            column: price
        "$.token_inner":
          - table: activities
            column: token_data_id
          - table: current_nft_marketplace_token_offers
            column: token_data_id
        "$.token_id.token_data_id.name":
          - table: activities
            column: token_name
          - table: current_nft_marketplace_token_offers
            column: token_name
        "$.token_id.token_data_id.creator":
          - table: activities
            column: creator_address
        "$.token_id.token_data_id.collection":
          - table: activities
            column: collection_name
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_token_offers
            column: collection_id

      # Collection Offers
      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CollectionBidEvent":
        "$.bid_id":
          - table: activities
            column: offer_id
          - table: current_nft_marketplace_collection_offers
            column: collection_offer_id
        "$.buyer":
          - table: activities
            column: buyer
          - table: current_nft_marketplace_collection_offers
            column: buyer
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_collection_offers
            column: price
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_collection_offers
            column: collection_id
        "$.creator":
          - table: activities
            column: creator_address
        "$.collection":
          - table: activities
            column: collection_name
        "$.amount":
          - table: activities
            column: token_amount
          - table: current_nft_marketplace_collection_offers
            column: remaining_token_amount
        "$.deadline":
          - table: activities
            column: expiration_time

      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelCollectionBidEvent":
        "$.bid_id":
          - table: activities
            column: offer_id
          - table: current_nft_marketplace_collection_offers
            column: collection_offer_id
        "$.buyer":
          - table: activities
            column: buyer
          - table: current_nft_marketplace_collection_offers
            column: buyer
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_collection_offers
            column: price
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_collection_offers
            column: collection_id
        "$.creator":
          - table: activities
            column: creator_address
        "$.collection":
          - table: activities
            column: collection_name

      "0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::FillCollectionBidEvent":
        "$.bid_id":
          - table: activities
            column: offer_id
          - table: current_nft_marketplace_collection_offers
            column: collection_offer_id
        "$.buyer":
          - table: activities
            column: buyer
          - table: current_nft_marketplace_collection_offers
            column: buyer
        "$.seller":
          - table: activities
            column: seller
        "$.price":
          - table: activities
            column: price
          - table: current_nft_marketplace_collection_offers
            column: price
        "$.token_inner":
          - table: activities
            column: token_data_id
        "$.token_id.token_data_id.name":
          - table: activities
            column: token_name
        "$.token_id.token_data_id.creator":
          - table: activities
            column: creator_address
        "$.token_id.token_data_id.collection":
          - table: activities
            column: collection_name
        "$.collection_inner":
          - table: activities
            column: collection_id
          - table: current_nft_marketplace_collection_offers
            column: collection_id